package com.ConferenceHall.entity;
// Generated 27 Mar, 2022 8:29:19 PM by Hibernate Tools 5.1.7.Final




import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * BookingTbl generated by hbm2java
 */
@Entity
@Table(name = "booking_tbl")
public class BookingTbl implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int bookingId;

	@JsonIgnore
	@ManyToOne
	@JoinColumn(name="confroom_id")
	private ConferenceRoomTbl conferenceRoomTbl;

	

	//bi-directional many-to-one association to UserInfoTbl
	@JsonIgnore
	@ManyToOne
	@JoinColumn(name="user_id")
	private UserInfoTbl userInfoTbl;
	
	//bi-directional many-to-one association to FeedbackTbl
	@OneToMany(mappedBy="bookingTbl")
	private Set<FeedbackTbl> feedbackTbls=new HashSet<FeedbackTbl>(0);
	
	private Date bookingDate;
	private Date bookingConferenceDate;
	//private Date bookingStartTime;
	//private Date bookingEndTime;
	private int bookingTotalGuests;
	private double bookingAmount;
	private String bookingStatus;



	public BookingTbl() {
	}

	public BookingTbl( ConferenceRoomTbl conferenceRoomTbl,  UserInfoTbl userInfoTbl,
			Date bookingDate, Date bookingConferenceDate, 
			int bookingTotalGuests, double bookingAmount, String bookingStatus) {
		
		this.conferenceRoomTbl = conferenceRoomTbl;
		
		this.userInfoTbl = userInfoTbl;
		this.bookingDate = bookingDate;
		this.bookingConferenceDate = bookingConferenceDate;
		//this.bookingStartTime = bookingStartTime;
		//this.bookingEndTime = bookingEndTime;
		this.bookingTotalGuests = bookingTotalGuests;
		this.bookingAmount = bookingAmount;
		this.bookingStatus = bookingStatus;
	}

	public BookingTbl( ConferenceRoomTbl conferenceRoomTbl,  UserInfoTbl userInfoTbl,
			Date bookingDate, Date bookingConferenceDate, 
			int bookingTotalGuests, double bookingAmount, String bookingStatus, Set<FeedbackTbl> feedbackTbls) {
		this.bookingId = bookingId;
		this.conferenceRoomTbl = conferenceRoomTbl;
		
		this.userInfoTbl = userInfoTbl;
		this.bookingDate = bookingDate;
		this.bookingConferenceDate = bookingConferenceDate;
		//this.bookingStartTime = bookingStartTime;
		//this.bookingEndTime = bookingEndTime;
		this.bookingTotalGuests = bookingTotalGuests;
		this.bookingAmount = bookingAmount;
		this.bookingStatus = bookingStatus;
		this.feedbackTbls = feedbackTbls;
	}

	@Id

	@Column(name = "booking_id", unique = true, nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "confroom_id", nullable = false)
	public ConferenceRoomTbl getConferenceRoomTbl() {
		return this.conferenceRoomTbl;
	}

	public void setConferenceRoomTbl(ConferenceRoomTbl conferenceRoomTbl) {
		this.conferenceRoomTbl = conferenceRoomTbl;
	}

	

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserInfoTbl getUserInfoTbl() {
		return this.userInfoTbl;
	}

	public void setUserInfoTbl(UserInfoTbl userInfoTbl) {
		this.userInfoTbl = userInfoTbl;
	}

	
	@Column(name = "booking_date", nullable = false, length = 10)
	public Date getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}


	@Column(name = "booking_conference_date", nullable = false, length = 10)
	public Date getBookingConferenceDate() {
		return this.bookingConferenceDate;
	}

	public void setBookingConferenceDate(Date bookingConferenceDate) {
		this.bookingConferenceDate = bookingConferenceDate;
	}

	/*
	 * @Temporal(TemporalType.TIME)
	 * 
	 * @Column(name = "booking_start_time", nullable = false, length = 8) public
	 * Date getBookingStartTime() { return this.bookingStartTime; }
	 * 
	 * public void setBookingStartTime(Date bookingStartTime) {
	 * this.bookingStartTime = bookingStartTime; }
	 */
	/*
	 * @Temporal(TemporalType.TIME)
	 * 
	 * @Column(name = "booking_end_time", nullable = false, length = 8) public Date
	 * getBookingEndTime() { return this.bookingEndTime; }
	 * 
	 * public void setBookingEndTime(Date bookingEndTime) { this.bookingEndTime =
	 * bookingEndTime; }
	 */

	@Column(name = "booking_total_guests", nullable = false)
	public int getBookingTotalGuests() {
		return this.bookingTotalGuests;
	}

	public void setBookingTotalGuests(int bookingTotalGuests) {
		this.bookingTotalGuests = bookingTotalGuests;
	}

	@Column(name = "booking_amount", nullable = false, precision = 22, scale = 0)
	public double getBookingAmount() {
		return this.bookingAmount;
	}

	public void setBookingAmount(double bookingAmount) {
		this.bookingAmount = bookingAmount;
	}

	@Column(name = "booking_status", nullable = false, length = 20)
	public String getBookingStatus() {
		return this.bookingStatus;
	}

	public void setBookingStatus(String bookingStatus) {
		this.bookingStatus = bookingStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookingTbl")
	public Set<FeedbackTbl> getFeedbackTbls() {
		return this.feedbackTbls;
	}

	public void setFeedbackTbls(Set<FeedbackTbl> feedbackTbls) {
		this.feedbackTbls = feedbackTbls;
	}

	@Override
	public String toString() {
		return "BookingTbl [bookingId=" + bookingId + ", conferenceRoomTbl=" + conferenceRoomTbl + ", hotelTbl="
				+ ", userInfoTbl=" + userInfoTbl + ", feedbackTbls=" + feedbackTbls + ", bookingDate="
				+ bookingDate + ", bookingConferenceDate=" + bookingConferenceDate + ", bookingTotalGuests="
				+ bookingTotalGuests + ", bookingAmount=" + bookingAmount + ", bookingStatus=" + bookingStatus + "]";
	}

	

}
