package com.ConferenceHall.entity;
// Generated 27 Mar, 2022 8:29:19 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ConferenceRoomTbl generated by hbm2java
 */
@Entity
@Table(name = "conference_room_tbl")
public class ConferenceRoomTbl implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int confroomId;
	@JsonIgnore
	@OneToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "hotelId", nullable = false,referencedColumnName = "hotelId")
	private HotelTbl hotelTbl;
	private String confroomName;
	private int confroomCapacity;
	private String confroomIsDining;
	private String confroomIsSmoking;
	private String confroomIsAc;
	private String confroomIsProjectorFacility;

	@OneToMany(mappedBy="conferenceRoomTbl")
	private Set<BookingTbl> bookingTbls = new HashSet<BookingTbl>(0);
	//bi-directional many-to-one association to ImageTbl
	@OneToMany(mappedBy="conferenceRoomTbl")
	private Set<ImageTbl> imageTbls = new HashSet<ImageTbl>(0);

	public ConferenceRoomTbl() {
	}

	public ConferenceRoomTbl(int confroomId, HotelTbl hotelTbl, String confroomName, int confroomCapacity,
			String confroomIsDining, String confroomIsSmoking, String confroomIsAc,
			String confroomIsProjectorFacility) {
		this.confroomId = confroomId;
		this.hotelTbl = hotelTbl;
		this.confroomName = confroomName;
		this.confroomCapacity = confroomCapacity;
		this.confroomIsDining = confroomIsDining;
		this.confroomIsSmoking = confroomIsSmoking;
		this.confroomIsAc = confroomIsAc;
		this.confroomIsProjectorFacility = confroomIsProjectorFacility;
	}

	public ConferenceRoomTbl(int confroomId, HotelTbl hotelTbl, String confroomName, int confroomCapacity,
			String confroomIsDining, String confroomIsSmoking, String confroomIsAc, String confroomIsProjectorFacility,
			Set<BookingTbl> bookingTbls, Set<ImageTbl> imageTbls) {
		this.confroomId = confroomId;
		this.hotelTbl = hotelTbl;
		this.confroomName = confroomName;
		this.confroomCapacity = confroomCapacity;
		this.confroomIsDining = confroomIsDining;
		this.confroomIsSmoking = confroomIsSmoking;
		this.confroomIsAc = confroomIsAc;
		this.confroomIsProjectorFacility = confroomIsProjectorFacility;
		this.bookingTbls = bookingTbls;
		this.imageTbls = imageTbls;
	}

	@Id

	@Column(name = "confroom_id", unique = true, nullable = false)
	public int getConfroomId() {
		return this.confroomId;
	}

	public void setConfroomId(int confroomId) {
		this.confroomId = confroomId;
	}

	@OneToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "hotelId", nullable = false,referencedColumnName = "hotel_id")
	public HotelTbl getHotelTbl() {
		return this.hotelTbl;
	}

	public void setHotelTbl(HotelTbl hotelTbl) {
		this.hotelTbl = hotelTbl;
	}

	@Column(name = "confroom_name", nullable = false, length = 50)
	public String getConfroomName() {
		return this.confroomName;
	}

	public void setConfroomName(String confroomName) {
		this.confroomName = confroomName;
	}

	@Column(name = "confroom_capacity", nullable = false)
	public int getConfroomCapacity() {
		return this.confroomCapacity;
	}

	public void setConfroomCapacity(int confroomCapacity) {
		this.confroomCapacity = confroomCapacity;
	}

	@Column(name = "confroom_isDining", nullable = false, length = 10)
	public String getConfroomIsDining() {
		return this.confroomIsDining;
	}

	public void setConfroomIsDining(String confroomIsDining) {
		this.confroomIsDining = confroomIsDining;
	}

	@Column(name = "confroom_isSmoking", nullable = false, length = 10)
	public String getConfroomIsSmoking() {
		return this.confroomIsSmoking;
	}

	public void setConfroomIsSmoking(String confroomIsSmoking) {
		this.confroomIsSmoking = confroomIsSmoking;
	}

	@Column(name = "confroom_isAC", nullable = false, length = 10)
	public String getConfroomIsAc() {
		return this.confroomIsAc;
	}

	public void setConfroomIsAc(String confroomIsAc) {
		this.confroomIsAc = confroomIsAc;
	}

	@Column(name = "confroom_isProjector_facility", nullable = false, length = 50)
	public String getConfroomIsProjectorFacility() {
		return this.confroomIsProjectorFacility;
	}

	public void setConfroomIsProjectorFacility(String confroomIsProjectorFacility) {
		this.confroomIsProjectorFacility = confroomIsProjectorFacility;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conferenceRoomTbl")
	public Set<BookingTbl> getBookingTbls() {
		return this.bookingTbls;
	}

	public void setBookingTbls(Set<BookingTbl> bookingTbls) {
		this.bookingTbls = bookingTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conferenceRoomTbl")
	public Set<ImageTbl> getImageTbls() {
		return this.imageTbls;
	}

	public void setImageTbls(Set<ImageTbl> imageTbls) {
		this.imageTbls = imageTbls;
	}

	@Override
	public String toString() {
		return "ConferenceRoomTbl [confroomId=" + confroomId + ", hotelTbl=" + hotelTbl + ", confroomName="
				+ confroomName + ", confroomCapacity=" + confroomCapacity + ", confroomIsDining=" + confroomIsDining
				+ ", confroomIsSmoking=" + confroomIsSmoking + ", confroomIsAc=" + confroomIsAc
				+ ", confroomIsProjectorFacility=" + confroomIsProjectorFacility + ", bookingTbls=" + bookingTbls
				+ ", imageTbls=" + imageTbls + "]";
	}

}
