package com.ConferenceHall.entity;
// Generated 27 Mar, 2022 8:29:19 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * HotelTbl generated by hbm2java
 */
@Entity
@Table(name = "hotel_tbl", catalog = "conference_management12")
public class HotelTbl implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int hotelId;
	private String hotelName;
	private String hotelUname;
	private String hotelPassword;
	private String hotelContactNumber;
	private String hotelContactPerson;
	private String hotelEmail;
	private String hotelIsParking;
	private String hotelCity;
	private String hotelDistrict;
	private String hotelState;
	private int hotelPincode;
	
	@OneToOne(mappedBy = "hotelTbl", fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	private ConferenceRoomTbl conferenceRoomTbls;
	
	public HotelTbl() {
	}

	public HotelTbl(int hotelId, String hotelName, String hotelUname, String hotelPassword, String hotelContactNumber,
			String hotelContactPerson, String hotelEmail, String hotelCity, String hotelDistrict, String hotelState,
			int hotelPincode) {
		this.hotelId = hotelId;
		this.hotelName = hotelName;
		this.hotelUname = hotelUname;
		this.hotelPassword = hotelPassword;
		this.hotelContactNumber = hotelContactNumber;
		this.hotelContactPerson = hotelContactPerson;
		this.hotelEmail = hotelEmail;
		this.hotelCity = hotelCity;
		this.hotelDistrict = hotelDistrict;
		this.hotelState = hotelState;
		this.hotelPincode = hotelPincode;
	}

	public HotelTbl(int hotelId, String hotelName, String hotelUname, String hotelPassword, String hotelContactNumber,
			String hotelContactPerson, String hotelEmail, String hotelIsParking, String hotelCity, String hotelDistrict,
			String hotelState, int hotelPincode,  ConferenceRoomTbl conferenceRoomTbls) {
		this.hotelId = hotelId;
		this.hotelName = hotelName;
		this.hotelUname = hotelUname;
		this.hotelPassword = hotelPassword;
		this.hotelContactNumber = hotelContactNumber;
		this.hotelContactPerson = hotelContactPerson;
		this.hotelEmail = hotelEmail;
		this.hotelIsParking = hotelIsParking;
		this.hotelCity = hotelCity;
		this.hotelDistrict = hotelDistrict;
		this.hotelState = hotelState;
		this.hotelPincode = hotelPincode;
		
		this.conferenceRoomTbls = conferenceRoomTbls;
	
	}

	@Id

	@Column(name = "hotel_id", unique = true, nullable = false)
	public int getHotelId() {
		return this.hotelId;
	}

	public void setHotelId(int hotelId) {
		this.hotelId = hotelId;
	}

	@Column(name = "hotel_name", nullable = false, length = 50)
	public String getHotelName() {
		return this.hotelName;
	}

	public void setHotelName(String hotelName) {
		this.hotelName = hotelName;
	}

	@Column(name = "hotel_uname", nullable = false, length = 50)
	public String getHotelUname() {
		return this.hotelUname;
	}

	public void setHotelUname(String hotelUname) {
		this.hotelUname = hotelUname;
	}

	@Column(name = "hotel_password", nullable = false, length = 15)
	public String getHotelPassword() {
		return this.hotelPassword;
	}

	public void setHotelPassword(String hotelPassword) {
		this.hotelPassword = hotelPassword;
	}

	@Column(name = "hotel_contact_number", nullable = false, length = 12)
	public String getHotelContactNumber() {
		return this.hotelContactNumber;
	}

	public void setHotelContactNumber(String hotelContactNumber) {
		this.hotelContactNumber = hotelContactNumber;
	}

	@Column(name = "hotel_contact_person", nullable = false, length = 50)
	public String getHotelContactPerson() {
		return this.hotelContactPerson;
	}

	public void setHotelContactPerson(String hotelContactPerson) {
		this.hotelContactPerson = hotelContactPerson;
	}

	@Column(name = "hotel_email", nullable = false, length = 50)
	public String getHotelEmail() {
		return this.hotelEmail;
	}

	public void setHotelEmail(String hotelEmail) {
		this.hotelEmail = hotelEmail;
	}

	@Column(name = "hotel_isParking", length = 10)
	public String getHotelIsParking() {
		return this.hotelIsParking;
	}

	public void setHotelIsParking(String hotelIsParking) {
		this.hotelIsParking = hotelIsParking;
	}

	@Column(name = "hotel_city", nullable = false, length = 20)
	public String getHotelCity() {
		return this.hotelCity;
	}

	public void setHotelCity(String hotelCity) {
		this.hotelCity = hotelCity;
	}

	@Column(name = "hotel_district", nullable = false, length = 20)
	public String getHotelDistrict() {
		return this.hotelDistrict;
	}

	public void setHotelDistrict(String hotelDistrict) {
		this.hotelDistrict = hotelDistrict;
	}

	@Column(name = "hotel_state", nullable = false, length = 20)
	public String getHotelState() {
		return this.hotelState;
	}

	public void setHotelState(String hotelState) {
		this.hotelState = hotelState;
	}

	@Column(name = "hotel_pincode", nullable = false)
	public int getHotelPincode() {
		return this.hotelPincode;
	}

	public void setHotelPincode(int hotelPincode) {
		this.hotelPincode = hotelPincode;
	}

	@OneToOne(mappedBy = "hotelTbl", fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	public ConferenceRoomTbl getConferenceRoomTbls() {
		return conferenceRoomTbls;
	}

	public void setConferenceRoomTbls(ConferenceRoomTbl conferenceRoomTbls) {
		this.conferenceRoomTbls = conferenceRoomTbls;
	}

	@Override
	public String toString() {
		return "HotelTbl [hotelId=" + hotelId + ", hotelName=" + hotelName + ", hotelUname=" + hotelUname
				+ ", hotelPassword=" + hotelPassword + ", hotelContactNumber=" + hotelContactNumber
				+ ", hotelContactPerson=" + hotelContactPerson + ", hotelEmail=" + hotelEmail + ", hotelIsParking="
				+ hotelIsParking + ", hotelCity=" + hotelCity + ", hotelDistrict=" + hotelDistrict + ", hotelState="
				+ hotelState + ", hotelPincode=" + hotelPincode + ", conferenceRoomTbls=" + conferenceRoomTbls + "]";
	}



}
