package com.ConferenceHall.entity;
// Generated 27 Mar, 2022 8:29:19 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ImageTbl generated by hbm2java
 */
@Entity
@Table(name = "image_tbl", catalog = "conference_management12")
public class ImageTbl implements java.io.Serializable {

	private int imageId;
	private ConferenceRoomTbl conferenceRoomTbl;
	
	private byte[] imageData;

	public ImageTbl() {
	}

	public ImageTbl(int imageId, byte[] imageData) {
		this.imageId = imageId;
	
		this.imageData = imageData;
	}

	public ImageTbl(int imageId, ConferenceRoomTbl conferenceRoomTbl, byte[] imageData) {
		this.imageId = imageId;
		this.conferenceRoomTbl = conferenceRoomTbl;

		this.imageData = imageData;
	}

	@Id

	@Column(name = "image_id", unique = true, nullable = false)
	public int getImageId() {
		return this.imageId;
	}

	public void setImageId(int imageId) {
		this.imageId = imageId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "confroom_id")
	public ConferenceRoomTbl getConferenceRoomTbl() {
		return this.conferenceRoomTbl;
	}

	public void setConferenceRoomTbl(ConferenceRoomTbl conferenceRoomTbl) {
		this.conferenceRoomTbl = conferenceRoomTbl;
	}


	@Column(name = "image_data", nullable = false)
	public byte[] getImageData() {
		return this.imageData;
	}

	public void setImageData(byte[] imageData) {
		this.imageData = imageData;
	}

}
