package com.ConferenceHall.entity;
// Generated 27 Mar, 2022 8:29:19 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * UserInfoTbl generated by hbm2java
 */
@Entity
@Table(name = "user_info_tbl", catalog = "conference_management12")
public class UserInfoTbl implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int userId;
	private String userFirstname;
	private String userLastname;
	private String userUname;
	private String userPassword;
	private String userContactNumber;
	private String userOccupation;
	private String userEmail;
	private String userCity;
	private String userDistrict;
	private String userState;
	private int userPin;
	@OneToOne
	private Set<FeedbackTbl> feedbackTbls = new HashSet<FeedbackTbl>(0);
	@OneToOne
	private Set<BookingTbl> bookingTbls = new HashSet<BookingTbl>(0);

	public UserInfoTbl() {
	}

	public UserInfoTbl(int userId, String userFirstname, String userLastname, String userUname, String userPassword,
			String userContactNumber, String userOccupation, String userEmail, String userCity, String userDistrict,
			String userState, int userPin) {
		this.userId = userId;
		this.userFirstname = userFirstname;
		this.userLastname = userLastname;
		this.userUname = userUname;
		this.userPassword = userPassword;
		this.userContactNumber = userContactNumber;
		this.userOccupation = userOccupation;
		this.userEmail = userEmail;
		this.userCity = userCity;
		this.userDistrict = userDistrict;
		this.userState = userState;
		this.userPin = userPin;
	}

	public UserInfoTbl(int userId, String userFirstname, String userLastname, String userUname, String userPassword,
			String userContactNumber, String userOccupation, String userEmail, String userCity, String userDistrict,
			String userState, int userPin, Set<FeedbackTbl> feedbackTbls, Set<BookingTbl> bookingTbls) {
		this.userId = userId;
		this.userFirstname = userFirstname;
		this.userLastname = userLastname;
		this.userUname = userUname;
		this.userPassword = userPassword;
		this.userContactNumber = userContactNumber;
		this.userOccupation = userOccupation;
		this.userEmail = userEmail;
		this.userCity = userCity;
		this.userDistrict = userDistrict;
		this.userState = userState;
		this.userPin = userPin;
		this.feedbackTbls = feedbackTbls;
		this.bookingTbls = bookingTbls;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "user_firstname", nullable = false, length = 50)
	public String getUserFirstname() {
		return this.userFirstname;
	}

	public void setUserFirstname(String userFirstname) {
		this.userFirstname = userFirstname;
	}

	@Column(name = "user_lastname", nullable = false, length = 50)
	public String getUserLastname() {
		return this.userLastname;
	}

	public void setUserLastname(String userLastname) {
		this.userLastname = userLastname;
	}

	@Column(name = "user_uname", nullable = false, length = 50)
	public String getUserUname() {
		return this.userUname;
	}

	public void setUserUname(String userUname) {
		this.userUname = userUname;
	}

	@Column(name = "user_password", nullable = false, length = 50)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_contact_number", nullable = false, length = 15)
	public String getUserContactNumber() {
		return this.userContactNumber;
	}

	public void setUserContactNumber(String userContactNumber) {
		this.userContactNumber = userContactNumber;
	}

	@Column(name = "user_occupation", nullable = false, length = 50)
	public String getUserOccupation() {
		return this.userOccupation;
	}

	public void setUserOccupation(String userOccupation) {
		this.userOccupation = userOccupation;
	}

	@Column(name = "user_email", nullable = false, length = 50)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_city", nullable = false, length = 20)
	public String getUserCity() {
		return this.userCity;
	}

	public void setUserCity(String userCity) {
		this.userCity = userCity;
	}

	@Column(name = "user_district", nullable = false, length = 20)
	public String getUserDistrict() {
		return this.userDistrict;
	}

	public void setUserDistrict(String userDistrict) {
		this.userDistrict = userDistrict;
	}

	@Column(name = "user_state", nullable = false, length = 20)
	public String getUserState() {
		return this.userState;
	}

	public void setUserState(String userState) {
		this.userState = userState;
	}

	@Column(name = "user_pin", nullable = false)
	public int getUserPin() {
		return this.userPin;
	}

	public void setUserPin(int userPin) {
		this.userPin = userPin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userInfoTbl")
	public Set<FeedbackTbl> getFeedbackTbls() {
		return this.feedbackTbls;
	}

	public void setFeedbackTbls(Set<FeedbackTbl> feedbackTbls) {
		this.feedbackTbls = feedbackTbls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userInfoTbl")
	public Set<BookingTbl> getBookingTbls() {
		return this.bookingTbls;
	}

	public void setBookingTbls(Set<BookingTbl> bookingTbls) {
		this.bookingTbls = bookingTbls;
	}

}
